linking with X11 needed:
to avoid: undefined reference to symbol 'XMapWindow' libX11.so error adding symbols: DSO missing from command line

https://stackoverflow.com/questions/46028923/dso-missing-from-command-line-in-libx11
https://github.com/tum-vision/lsd_slam/issues/29